### ISSUE TITLE
Searching by short tags

### ISSUE THREAD

**Issue by l-kutik** [lasselehtinen/onix-codelist#1]
Hello! This is a great idea, thank you for sharing!

It would be helpful to also be able to search by short tags, for example, j141/x462 or j261 instead of Price Type Code and Price Type Qualifier.

**Comment by lasselehtinen** [comment]
So basically you want to be able to search for Onix element names either the normal or short ones and it would show the codelist(s) that the element uses? And vice versa if I search for codelist it would also show the elements that utilize the codelist. So for example searching for 'DefaultPriceType' or the short tag 'x310' would return codelist 58. And searching for 'Price type code' would return the elements that utilize it, like 'DefaultPriceType' in our example. Did I understood your use case correctly?

That might get little bit tricky since one codelist could be used by multiple different fields. I guess I could try to parse one of the schemes to determine which elements are actually using a codelist and index those. I can promise to look into it at least.

**Comment by lasselehtinen** [comment]
I've now indexed the elements that reference to Onix codelists. I've included both the reference and the short name of the elements. I had to disable the typo tolerant search on the short name field so you need to type in the exact match. Without it search would return other elements as well. Fuzzy search still works on the reference name though.

The reverse search also works, for example 'country code' returns all four elements using "List 91: Country code – ISO 3166-1".

Can you test this out so I can close the issue?

**Comment by l-kutik** [comment]
Tested with j261 - works well! Thanks very much for adding this feature.

**Comment by renekmendrun** [comment]
Lasse, thanks! At the very first glance works very well. 

I'm working as a project manager at the ISBN Agency in Poland (which btw is a part of the National Library). We have developed an ONIX based and free of charge service for publishers, and at the moment we are trying to map ONIX 3.0 to MARC21 and MARC21 to ONIX 3.0.  So quite often I run back and forth through ONIX lists knowing that ...it should be somewhere in here….

I'll come later with remarks

Renek Mendrun
