### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by peterfleck** [lasselehtinen/onix-codelist#3]
Would it be possible to add the Spanish translations?

https://www.dilve.es/dilve/dilveweb/dilve_documentaciononix.jsp
Listas de códigos ONIX Ed. 33 (XML) - https://www.dilve.es/dilve/getArchivoDocumentacion.do?iddocumento=2123

Thanks

**Comment by lasselehtinen** [comment]
Hi,

Sorry for the long delay. I tried to work on this at some point, but it proved quite difficult since this was a quick weekend project and I did not really built it to support multiple languages from the start. But EDItEUR has now launched the official Onix codelist browser which has support for all the languages, including spanish. So hope you are fine using that one?

https://ns.editeur.org/onix/es

**Comment by peterfleck** [comment]
That's great @lasselehtinen. Many thanks for your work on this.
