### ISSUE TITLE
Great work, Lasse!

### ISSUE THREAD

**Issue by MarionSeelig** [lasselehtinen/onix-codelist#4]
Hi Lasse,
I might have mentioned before that we love your work :-)
Not only the german Bonnier-staff is working with your onix-codelist but many more german publishers...

As editeur announced the codelist issue 39 today I wondered if changes coming from issue 38 are online?
Thanks again for spending your time on this project,
Marion

**Comment by lasselehtinen** [comment]
Hi Marion, 

Thanks for the feedback! I also happen to work for Bonnier here in Finland. If the service is popular in Germany, maybe I should make this 🍺 ware. As you probably are aware, EDItEUR has now launched their [own Onix codelist browser](https://ns.editeur.org/onix/). So I might shutdown my hosted service at some point. But since the hosting doesn't that cost much, I am not in a hurry.

I've updated to the latest codelist issue (39) now.
