### ISSUE TITLE
get the database

### ISSUE THREAD

**Issue by karamqubsi** [lasselehtinen/onix-codelist#5]
Hi , thanks for the great efforts , it is really useful tool , but is the database available as well ? do you have seeds for it ?

Thanks.

**Comment by lasselehtinen** [comment]
Hi,

The seeding is done be the two commands listed below. Now that I think about it, these could be moved to database seeders instead of commands. Basically they parse the official Onix codelists from JSON and then insert the models to the database. Does this answer your question?

https://github.com/lasselehtinen/onix-codelist/blob/master/app/Console/Commands/UpdateCodelists.php
https://github.com/lasselehtinen/onix-codelist/blob/master/app/Console/Commands/UpdateElements.php

**Comment by karamqubsi** [comment]
That's great thank you very much.

**Comment by karamqubsi** [comment]
Hi I've tried that out , I got the codelist seed in my local db  after making a minor modification on "UpdateCodelists.php" 
Perhaps  the onix freed structure has been changed from how it used to be

**Comment by karamqubsi** [comment]
I will make a pull request if you find it useful to merge it :) , 

Thanks again for the help

**Comment by lasselehtinen** [comment]
The PR has been now merged. Seems like they indeed changed the JSON structure at some point.
